# Generated by Django 4.1.7 on 2023-03-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=200)),
                ('duration', models.IntegerField()),
                ('img', models.ImageField(upload_to='pic')),
                ('speed', models.FloatField()),
                ('data', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
